include ../config.mak                        # paths

# set VPATH path for targets and src files
VPATH = $(SRCDIR)/spec-tests

EXTRA_FLAGS := --disable-dst-to-src-submap --smt-query-timeout 5

UNROLL1_SPEC :=               \
                edge1         \
                edge2         \
                edge3         \
                              \
                cond1         \
                cond2         \
                cond3         \
                              \
                loop1         \
                loop2         \
                loop3         \
                loop4         \
                loop5         \
                loop6         \
                loop7         \
                              \
                couple1       \
                couple2       \
                couple3       \
                couple4       \
                couple5       \
                couple6       \
                couple7       \
                couple8       \
                              \
                ind1          \
                ind2          \
                ind3          \
                ind4          \
                ind5          \
                ind6          \
                              \
                fcall1        \
                fcall2        \
                fcall3        \
                fcall4        \
                fcall5        \
                              \
                # ind7          \
                # ind8          \
                # ind9          \

include $(SRCDIR)/Makefile.template
