include ../config.mak                        # paths

# set VPATH path for targets and src files
VPATH = $(SRCDIR)/bzip2

UNROLL1_GCC = bzip2
UNROLL1_CLANG = bzip2

include $(SRCDIR)/Makefile.template
