include ../config.mak                        # paths

# set VPATH path for targets and src files
VPATH = $(SRCDIR)/cpp

UNROLL1_GPP =
UNROLL1_CLANGPP =
EXTRA_FLAGS := --smt-query-timeout 1200 --global-timeout 9000

C_STD = gnu11
include $(SRCDIR)/Makefile.template
