#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include <wchar.h>
#include <time.h>
#include <unistd.h>

void *memccpy_dietlibc(void *dest, const void *src, int c, size_t n);
void *memccpy_freebsd(void *dest, const void *src, int c, size_t n);
void *memccpy_klibc(void *dest, const void *src, int c, size_t n);
void *memccpy_musl(void *dest, const void *src, int c, size_t n);
void *memccpy_netbsd(void *dest, const void *src, int c, size_t n);
void *memccpy_newlib_fast(void *dest, const void *src, int c, size_t n);
void *memccpy_newlib_fast_patched(void *dest, const void *src, int c, size_t n);
void *memccpy_openbsd(void *dest, const void *src, int c, size_t n);
void *memchr_dietlibc(const void *s, int c, size_t n);
void *memchr_dietlibc_contrib_fast(const void *s, int c, size_t n);
void *memchr_freebsd(const void *s, int c, size_t n);
void *memchr_glibc(const void *s, int c, size_t n);
void *memchr_klibc(const void *s, int c, size_t n);
void *memchr_newlib_fast(const void *s, int c, size_t n);
void *memcpy_dietlibc_fast(void *dest, const void *src, size_t n);
void *memcpy_dietlibc_small(void *dest, const void *src, size_t n);
void *memcpy_freebsd(void *dest, const void *src, size_t n);
void *memcpy_musl(void *dest, const void *src, size_t n);
void *memcpy_netbsd_fast(void *dest, const void *src, size_t n);
void *memcpy_netbsd_small(void *dest, const void *src, size_t n);
void *memcpy_newlib_fast(void *dest, const void *src, size_t n);
void *memcpy_newlib_small(void *dest, const void *src, size_t n);
void *memcpy_openbsd(void *dest, const void *src, size_t n);
void *memcpy_openbsd_m88k(void *dest, const void *src, size_t n);
void *memrchr_dietlibc(const void *s, int c, size_t n);
void *memrchr_freebsd(const void *s, int c, size_t n);
void *memrchr_glibc(const void *s, int c, size_t n);
void *memrchr_klibc(const void *s, int c, size_t n);
void *memrchr_musl(const void *s, int c, size_t n);
void *memrchr_newlib_fast(const void *s, int c, size_t n);
char *stpncpy_freebsd(char *dest, const char *src, size_t n);
char *stpncpy_newlib_small(char *dest, const char *src, size_t n);
int strcasecmp_dietlibc(const char *s1, const char *s2);
int strcasecmp_netbsd_distrib(const char *s1, const char *s2);
int strcasecmp_openbsd(const char *s1, const char *s2);
int strcmp_dietlibc_fast(const char *s1, const char *s2);
int strcmp_dietlibc_fast_patched(const char *s1, const char *s2);
int strcmp_dietlibc_small(const char *s1, const char *s2);
int strcmp_dietlibc_small_patched(const char *s1, const char *s2);
int strcmp_freebsd(const char *s1, const char *s2);
int strcmp_glibc(const char *s1, const char *s2);
int strcmp_newlib_small(const char *s1, const char *s2);
size_t strlcpy_dietlibc(char *dest, const char *src, size_t size);
size_t strlcpy_klibc(char *dest, const char *src, size_t size);
size_t strlcpy_netbsd(char *dest, const char *src, size_t size);
size_t strlcpy_newlib(char *dest, const char *src, size_t size);
size_t strlen_dietlibc_small(const char *s);
size_t strlen_glibc(const char *s);
size_t strlen_klibc(const char *s);
size_t strlen_newlib(const char *s);
int strncasecmp_dietlibc(const char *s1, const char *s2, size_t n);
int strncasecmp_openbsd(const char *s1, const char *s2, size_t n);
char *strrchr_dietlibc_small(const char *s, int c);
char *strrchr_klibc(const char *s, int c);
char *strrchr_klibc_patched(const char *s, int c);
char *strrchr_netbsd(const char *s, int c);
void swab_dietlibc(const void *from, void *to, ssize_t n);
void swab_dietlibc_patched(const void *from, void *to, ssize_t n);
void swab_freebsd(const void *from, void *to, ssize_t n);
void swab_freebsd_heimdal(const void *from, void *to, ssize_t n);
void swab_glibc(const void *from, void *to, ssize_t n);
void swab_musl(const void *from, void *to, ssize_t n);
void swab_musl_patched(const void *from, void *to, ssize_t n);
void swab_netbsd(const void *from, void *to, ssize_t n);
void swab_netbsd_heimdal(const void *from, void *to, ssize_t n);
void swab_netbsd_patched(const void *from, void *to, ssize_t n);
void swab_newlib(const void *from, void *to, ssize_t n);
void swab_openbsd(const void *from, void *to, ssize_t n);
void swab_uClibc(const void *from, void *to, ssize_t n);
wchar_t *wcschr_dietlibc(const wchar_t *wcs, wchar_t wc);
wchar_t *wcschr_freebsd(const wchar_t *wcs, wchar_t wc);
wchar_t *wcschr_glibc(const wchar_t *wcs, wchar_t wc);
wchar_t *wcschr_netbsd(const wchar_t *wcs, wchar_t wc);
wchar_t *wcschr_openbsd(const wchar_t *wcs, wchar_t wc);
int wcscmp_dietlibc(const wchar_t *s1, const wchar_t *s2);
int wcscmp_freebsd(const wchar_t *s1, const wchar_t *s2);
int wcscmp_glibc(const wchar_t *s1, const wchar_t *s2);
int wcscmp_openbsd(const wchar_t *s1, const wchar_t *s2);
int wcscmp_uClibc(const wchar_t *s1, const wchar_t *s2);
int wcsncmp_dietlibc(const wchar_t *s1, const wchar_t *s2, size_t n);
int wcsncmp_freebsd(const wchar_t *s1, const wchar_t *s2, size_t n);
int wcsncmp_glibc(const wchar_t *s1, const wchar_t *s2, size_t n);
int wcsncmp_musl(const wchar_t *s1, const wchar_t *s2, size_t n);
int wcsncmp_openbsd(const wchar_t *s1, const wchar_t *s2, size_t n);
int wcsncmp_uClibc(const wchar_t *s1, const wchar_t *s2, size_t n);
wchar_t *wcsrchr_dietlibc(const wchar_t *wcs, wchar_t wc);
wchar_t *wcsrchr_freebsd(const wchar_t *wcs, wchar_t wc);
wchar_t *wcsrchr_glibc(const wchar_t *wcs, wchar_t wc);
wchar_t *wcsrchr_netbsd(const wchar_t *wcs, wchar_t wc);
wchar_t *wcsrchr_openbsd(const wchar_t *wcs, wchar_t wc);
wchar_t *wcsrchr_uClibc(const wchar_t *wcs, wchar_t wc);
wchar_t *wcsstr_dietlibc(const wchar_t *haystack, const wchar_t *needle);
wchar_t *wcsstr_uClibc(const wchar_t *haystack, const wchar_t *needle);
int wmemcmp_dietlibc(const wchar_t *s1, const wchar_t *s2, size_t n);
int wmemcmp_freebsd(const wchar_t *s1, const wchar_t *s2, size_t n);
int wmemcmp_glibc(const wchar_t *s1, const wchar_t *s2, size_t n);
int wmemcmp_musl(const wchar_t *s1, const wchar_t *s2, size_t n);
int wmemcmp_netbsd(const wchar_t *s1, const wchar_t *s2, size_t n);
int wmemcmp_newlib(const wchar_t *s1, const wchar_t *s2, size_t n);
int wmemcmp_uClibc(const wchar_t *s1, const wchar_t *s2, size_t n);
