include ../config.mak                        # paths

# set VPATH path for targets and src files
VPATH = $(SRCDIR)/bzip2-modified

UNROLL1_GCC = bzip2
UNROLL1_CLANG = bzip2

# # unroll8 functions
# initUnzftab
# setUpcftabAlso
# initToZero
# initWeightUsingfreq
# initpos
# initrunningOrder
# sendMTFValues

include $(SRCDIR)/Makefile.template
